var annotated_dup =
[
    [ "BlobertArena", "namespace_blobert_arena.html", [
      [ "Animations", "namespace_blobert_arena_1_1_animations.html", [
        [ "AmmaAnimationController", "class_blobert_arena_1_1_animations_1_1_amma_animation_controller.html", "class_blobert_arena_1_1_animations_1_1_amma_animation_controller" ],
        [ "AmmaAnimationData", "class_blobert_arena_1_1_animations_1_1_amma_animation_data.html", null ],
        [ "AnimationEntry", "struct_blobert_arena_1_1_animations_1_1_animation_entry.html", null ],
        [ "CharacterAnimationManager", "class_blobert_arena_1_1_animations_1_1_character_animation_manager.html", "class_blobert_arena_1_1_animations_1_1_character_animation_manager" ]
      ] ],
      [ "TestingScript", "namespace_blobert_arena_1_1_testing_script.html", [
        [ "SwitchSceneTester", "class_blobert_arena_1_1_testing_script_1_1_switch_scene_tester.html", null ],
        [ "TestingCharacterAnimationComponent", "class_blobert_arena_1_1_testing_script_1_1_testing_character_animation_component.html", null ]
      ] ],
      [ "Tests", "namespace_blobert_arena_1_1_tests.html", [
        [ "TestingManager", "class_blobert_arena_1_1_tests_1_1_testing_manager.html", null ]
      ] ],
      [ "ThemeManager", "namespace_blobert_arena_1_1_theme_manager.html", [
        [ "ColorMapping", "struct_blobert_arena_1_1_theme_manager_1_1_color_mapping.html", "struct_blobert_arena_1_1_theme_manager_1_1_color_mapping" ],
        [ "ColorPaletteThemeManager", "class_blobert_arena_1_1_theme_manager_1_1_color_palette_theme_manager.html", "class_blobert_arena_1_1_theme_manager_1_1_color_palette_theme_manager" ],
        [ "GameBackgroundComponent", "class_blobert_arena_1_1_theme_manager_1_1_game_background_component.html", null ],
        [ "ImageThemeManager", "class_blobert_arena_1_1_theme_manager_1_1_image_theme_manager.html", "class_blobert_arena_1_1_theme_manager_1_1_image_theme_manager" ],
        [ "StandardButtonThemeListener", "class_blobert_arena_1_1_theme_manager_1_1_standard_button_theme_listener.html", null ],
        [ "SwitchThemeListener", "class_blobert_arena_1_1_theme_manager_1_1_switch_theme_listener.html", null ],
        [ "ThemeImageListener", "class_blobert_arena_1_1_theme_manager_1_1_theme_image_listener.html", null ],
        [ "ThemesManager", "class_blobert_arena_1_1_theme_manager_1_1_themes_manager.html", null ],
        [ "ToggleButtonThemeListener", "class_blobert_arena_1_1_theme_manager_1_1_toggle_button_theme_listener.html", null ]
      ] ]
    ] ],
    [ "LogicLayer", "namespace_logic_layer.html", [
      [ "Models", "namespace_logic_layer_1_1_models.html", [
        [ "amma_blobert_AttackSlot", "class_logic_layer_1_1_models_1_1amma__blobert___attack_slot.html", "class_logic_layer_1_1_models_1_1amma__blobert___attack_slot" ],
        [ "amma_blobert_BlobertItem", "class_logic_layer_1_1_models_1_1amma__blobert___blobert_item.html", "class_logic_layer_1_1_models_1_1amma__blobert___blobert_item" ],
        [ "amma_blobert_BlobertToken", "class_logic_layer_1_1_models_1_1amma__blobert___blobert_token.html", "class_logic_layer_1_1_models_1_1amma__blobert___blobert_token" ],
        [ "arcade_blobert_BlobertToken", "class_logic_layer_1_1_models_1_1arcade__blobert___blobert_token.html", "class_logic_layer_1_1_models_1_1arcade__blobert___blobert_token" ],
        [ "betsy_Bet", "class_logic_layer_1_1_models_1_1betsy___bet.html", "class_logic_layer_1_1_models_1_1betsy___bet" ],
        [ "blob_arena_Attack", "class_logic_layer_1_1_models_1_1blob__arena___attack.html", "class_logic_layer_1_1_models_1_1blob__arena___attack" ],
        [ "blob_arena_AttackName", "class_logic_layer_1_1_models_1_1blob__arena___attack_name.html", "class_logic_layer_1_1_models_1_1blob__arena___attack_name" ],
        [ "blob_arena_AvailableAttack", "class_logic_layer_1_1_models_1_1blob__arena___available_attack.html", "class_logic_layer_1_1_models_1_1blob__arena___available_attack" ],
        [ "blob_arena_CombatantInfo", "class_logic_layer_1_1_models_1_1blob__arena___combatant_info.html", "class_logic_layer_1_1_models_1_1blob__arena___combatant_info" ],
        [ "blob_arena_CombatantState", "class_logic_layer_1_1_models_1_1blob__arena___combatant_state.html", "class_logic_layer_1_1_models_1_1blob__arena___combatant_state" ],
        [ "blob_arena_CombatantToken", "class_logic_layer_1_1_models_1_1blob__arena___combatant_token.html", "class_logic_layer_1_1_models_1_1blob__arena___combatant_token" ],
        [ "blob_arena_CombatEnd", "class_logic_layer_1_1_models_1_1blob__arena___combat_end.html", "class_logic_layer_1_1_models_1_1blob__arena___combat_end" ],
        [ "blob_arena_CombatState", "class_logic_layer_1_1_models_1_1blob__arena___combat_state.html", "class_logic_layer_1_1_models_1_1blob__arena___combat_state" ],
        [ "blob_arena_Commitment", "class_logic_layer_1_1_models_1_1blob__arena___commitment.html", "class_logic_layer_1_1_models_1_1blob__arena___commitment" ],
        [ "blob_arena_GameInfo", "class_logic_layer_1_1_models_1_1blob__arena___game_info.html", "class_logic_layer_1_1_models_1_1blob__arena___game_info" ],
        [ "blob_arena_Initiator", "class_logic_layer_1_1_models_1_1blob__arena___initiator.html", "class_logic_layer_1_1_models_1_1blob__arena___initiator" ],
        [ "blob_arena_LastTimestamp", "class_logic_layer_1_1_models_1_1blob__arena___last_timestamp.html", "class_logic_layer_1_1_models_1_1blob__arena___last_timestamp" ],
        [ "blob_arena_Lobby", "class_logic_layer_1_1_models_1_1blob__arena___lobby.html", "class_logic_layer_1_1_models_1_1blob__arena___lobby" ],
        [ "blob_arena_PlannedAttack", "class_logic_layer_1_1_models_1_1blob__arena___planned_attack.html", "class_logic_layer_1_1_models_1_1blob__arena___planned_attack" ],
        [ "blob_arena_RoundResult", "class_logic_layer_1_1_models_1_1blob__arena___round_result.html", "class_logic_layer_1_1_models_1_1blob__arena___round_result" ],
        [ "blobert_AttackSlot", "class_logic_layer_1_1_models_1_1blobert___attack_slot.html", "class_logic_layer_1_1_models_1_1blobert___attack_slot" ],
        [ "blobert_BlobertItem", "class_logic_layer_1_1_models_1_1blobert___blobert_item.html", "class_logic_layer_1_1_models_1_1blobert___blobert_item" ],
        [ "blobert_BlobertItemName", "class_logic_layer_1_1_models_1_1blobert___blobert_item_name.html", "class_logic_layer_1_1_models_1_1blobert___blobert_item_name" ],
        [ "DetailedAttackOutcome", "struct_logic_layer_1_1_models_1_1_detailed_attack_outcome.html", null ],
        [ "EffectDetails", "struct_logic_layer_1_1_models_1_1_effect_details.html", null ],
        [ "Fee", "struct_logic_layer_1_1_models_1_1_fee.html", null ],
        [ "IAttack", "interface_logic_layer_1_1_models_1_1_i_attack.html", "interface_logic_layer_1_1_models_1_1_i_attack" ],
        [ "IAttackName", "interface_logic_layer_1_1_models_1_1_i_attack_name.html", "interface_logic_layer_1_1_models_1_1_i_attack_name" ],
        [ "IAttackSlot", "interface_logic_layer_1_1_models_1_1_i_attack_slot.html", "interface_logic_layer_1_1_models_1_1_i_attack_slot" ],
        [ "IAvailableAttack", "interface_logic_layer_1_1_models_1_1_i_available_attack.html", "interface_logic_layer_1_1_models_1_1_i_available_attack" ],
        [ "IBet", "interface_logic_layer_1_1_models_1_1_i_bet.html", "interface_logic_layer_1_1_models_1_1_i_bet" ],
        [ "IBlobertItem", "interface_logic_layer_1_1_models_1_1_i_blobert_item.html", "interface_logic_layer_1_1_models_1_1_i_blobert_item" ],
        [ "IBlobertItemName", "interface_logic_layer_1_1_models_1_1_i_blobert_item_name.html", "interface_logic_layer_1_1_models_1_1_i_blobert_item_name" ],
        [ "IBlobertToken", "interface_logic_layer_1_1_models_1_1_i_blobert_token.html", "interface_logic_layer_1_1_models_1_1_i_blobert_token" ],
        [ "ICombatantInfo", "interface_logic_layer_1_1_models_1_1_i_combatant_info.html", "interface_logic_layer_1_1_models_1_1_i_combatant_info" ],
        [ "ICombatantState", "interface_logic_layer_1_1_models_1_1_i_combatant_state.html", "interface_logic_layer_1_1_models_1_1_i_combatant_state" ],
        [ "ICombatantToken", "interface_logic_layer_1_1_models_1_1_i_combatant_token.html", "interface_logic_layer_1_1_models_1_1_i_combatant_token" ],
        [ "ICombatEnd", "interface_logic_layer_1_1_models_1_1_i_combat_end.html", "interface_logic_layer_1_1_models_1_1_i_combat_end" ],
        [ "ICombatState", "interface_logic_layer_1_1_models_1_1_i_combat_state.html", "interface_logic_layer_1_1_models_1_1_i_combat_state" ],
        [ "IGameInfo", "interface_logic_layer_1_1_models_1_1_i_game_info.html", "interface_logic_layer_1_1_models_1_1_i_game_info" ],
        [ "IInitiator", "interface_logic_layer_1_1_models_1_1_i_initiator.html", "interface_logic_layer_1_1_models_1_1_i_initiator" ],
        [ "ILastTimestamp", "interface_logic_layer_1_1_models_1_1_i_last_timestamp.html", "interface_logic_layer_1_1_models_1_1_i_last_timestamp" ],
        [ "ILobby", "interface_logic_layer_1_1_models_1_1_i_lobby.html", "interface_logic_layer_1_1_models_1_1_i_lobby" ],
        [ "IPlannedAttack", "interface_logic_layer_1_1_models_1_1_i_planned_attack.html", "interface_logic_layer_1_1_models_1_1_i_planned_attack" ],
        [ "IRoundResult", "interface_logic_layer_1_1_models_1_1_i_round_result.html", "interface_logic_layer_1_1_models_1_1_i_round_result" ],
        [ "Wager", "struct_logic_layer_1_1_models_1_1_wager.html", null ],
        [ "WalletBlobert", "class_logic_layer_1_1_models_1_1_wallet_blobert.html", "class_logic_layer_1_1_models_1_1_wallet_blobert" ]
      ] ],
      [ "Query", "namespace_logic_layer_1_1_query.html", [
        [ "AffectData", "class_logic_layer_1_1_query_1_1_affect_data.html", null ],
        [ "DamageData", "class_logic_layer_1_1_query_1_1_damage_data.html", null ],
        [ "Edge", "class_logic_layer_1_1_query_1_1_edge.html", null ],
        [ "Entity", "class_logic_layer_1_1_query_1_1_entity.html", null ],
        [ "HitData", "class_logic_layer_1_1_query_1_1_hit_data.html", null ],
        [ "IData", "interface_logic_layer_1_1_query_1_1_i_data.html", null ],
        [ "Models", "class_logic_layer_1_1_query_1_1_models.html", null ],
        [ "Node", "class_logic_layer_1_1_query_1_1_node.html", null ],
        [ "SeedData", "class_logic_layer_1_1_query_1_1_seed_data.html", null ],
        [ "StatData", "class_logic_layer_1_1_query_1_1_stat_data.html", null ],
        [ "StatsData", "class_logic_layer_1_1_query_1_1_stats_data.html", null ],
        [ "TokenTraitData", "class_logic_layer_1_1_query_1_1_token_trait_data.html", null ]
      ] ],
      [ "SynchroManagerDojo", "class_logic_layer_1_1_synchro_manager_dojo.html", null ],
      [ "WorldManagerDojo", "class_logic_layer_1_1_world_manager_dojo.html", null ]
    ] ],
    [ "UiComponents", "namespace_ui_components.html", [
      [ "Slider", "namespace_ui_components_1_1_slider.html", [
        [ "SliderAnimatorComponent", "class_ui_components_1_1_slider_1_1_slider_animator_component.html", "class_ui_components_1_1_slider_1_1_slider_animator_component" ]
      ] ]
    ] ],
    [ "AboutPopup", "class_about_popup.html", null ],
    [ "AnimatedArrow", "class_animated_arrow.html", null ],
    [ "AnimationBase", "class_animation_base.html", "class_animation_base" ],
    [ "AnimationDataEditor", "class_animation_data_editor.html", null ],
    [ "ArcadeSubMenu", "class_arcade_sub_menu.html", null ],
    [ "ArrowInteractionText", "class_arrow_interaction_text.html", null ],
    [ "AudioManager", "class_audio_manager.html", "class_audio_manager" ],
    [ "AvailableAttackListComponent", "class_available_attack_list_component.html", null ],
    [ "AvailableAttackListElement", "class_available_attack_list_element.html", null ],
    [ "AvailableBlobListComponent", "class_available_blob_list_component.html", null ],
    [ "AvailableBlobListElement", "class_available_blob_list_element.html", null ],
    [ "BattlePageAnimation", "class_battle_page_animation.html", null ],
    [ "BlobChoosenListener", "class_blob_choosen_listener.html", null ],
    [ "BlobDataViewerComponent", "class_blob_data_viewer_component.html", null ],
    [ "BlobDexComponent", "class_blob_dex_component.html", null ],
    [ "BlobDexInfoContainerComponent", "class_blob_dex_info_container_component.html", "class_blob_dex_info_container_component" ],
    [ "BloberingAnimation", "class_blobering_animation.html", null ],
    [ "BlobertEffectsAnimationComponent", "class_blobert_effects_animation_component.html", null ],
    [ "BlobertEntityTester", "class_blobert_entity_tester.html", null ],
    [ "BlobertTraitsEnum", "class_blobert_traits_enum.html", "class_blobert_traits_enum" ],
    [ "BlobTypeData", "class_blob_type_data.html", null ],
    [ "BottomBar", "class_bottom_bar.html", null ],
    [ "BottomBarButton", "class_bottom_bar_button.html", null ],
    [ "BottomBarManager", "class_bottom_bar_manager.html", null ],
    [ "BuildScript", "class_build_script.html", null ],
    [ "ChallengeSubMenu", "class_challenge_sub_menu.html", null ],
    [ "CharacterStatsVisualizerComponent", "class_character_stats_visualizer_component.html", null ],
    [ "CheckBoxTextTester", "class_check_box_text_tester.html", null ],
    [ "ChooseBlobertForTournamentPageBehaviour", "class_choose_blobert_for_tournament_page_behaviour.html", null ],
    [ "ClickOnSpecificTraitComponent", "class_click_on_specific_trait_component.html", null ],
    [ "ColourableComponent", "struct_colourable_component.html", null ],
    [ "ColourableComponentDrawer", "class_colourable_component_drawer.html", null ],
    [ "CombatAnimations", "class_combat_animations.html", null ],
    [ "CombatBagButton", "class_combat_bag_button.html", null ],
    [ "CombatEntityTester", "class_combat_entity_tester.html", null ],
    [ "CombatInfoPopup", "class_combat_info_popup.html", null ],
    [ "CombatMovesPopup", "class_combat_moves_popup.html", null ],
    [ "CombatPage", "class_combat_page.html", null ],
    [ "ConfirmationPopup", "class_confirmation_popup.html", null ],
    [ "ContactUs", "class_contact_us.html", null ],
    [ "Counter", "class_counter.html", null ],
    [ "CursorManager", "class_cursor_manager.html", null ],
    [ "CustomPolygonGraphUI", "class_custom_polygon_graph_u_i.html", null ],
    [ "DynamicOverlayButton", "class_dynamic_overlay_button.html", null ],
    [ "EffectPlayer", "class_effect_player.html", null ],
    [ "EndOfBattle", "class_end_of_battle.html", null ],
    [ "FightFilterPopup", "class_fight_filter_popup.html", null ],
    [ "FightMenuPage", "class_fight_menu_page.html", null ],
    [ "FightSubMenu", "class_fight_sub_menu.html", null ],
    [ "FirstRollPage", "class_first_roll_page.html", null ],
    [ "FolderDescriptionPopup", "class_folder_description_popup.html", null ],
    [ "FolderInspectorWithDescription", "class_folder_inspector_with_description.html", null ],
    [ "GameEntityTester", "class_game_entity_tester.html", null ],
    [ "GameManager", "class_game_manager.html", null ],
    [ "GameStateSpawner", "class_game_state_spawner.html", "class_game_state_spawner" ],
    [ "GifPlayer", "class_gif_player.html", "class_gif_player" ],
    [ "ICommitment", "interface_i_commitment.html", null ],
    [ "IDebugPrintOut", "interface_i_debug_print_out.html", "interface_i_debug_print_out" ],
    [ "ILobbyListElement", "interface_i_lobby_list_element.html", null ],
    [ "InLobbyOngoingLobbyListPageElement", "class_in_lobby_ongoing_lobby_list_page_element.html", null ],
    [ "InputManager", "class_input_manager.html", null ],
    [ "InteractableTextComponent", "class_interactable_text_component.html", null ],
    [ "InvSentOnGoingLobbyListPageElement", "class_inv_sent_on_going_lobby_list_page_element.html", null ],
    [ "LeaderBoardPageBehaviour", "class_leader_board_page_behaviour.html", null ],
    [ "LeaderboardPlacement", "struct_leaderboard_placement.html", null ],
    [ "LeaderboardPopup", "class_leaderboard_popup.html", null ],
    [ "LeaveGamePopup", "class_leave_game_popup.html", null ],
    [ "LiveFightsComponent", "class_live_fights_component.html", null ],
    [ "LoadVersionManager", "class_load_version_manager.html", null ],
    [ "LoginPageAnimation", "class_login_page_animation.html", null ],
    [ "LoginPageBehaviour", "class_login_page_behaviour.html", null ],
    [ "MainMenuPageBehavior", "class_main_menu_page_behavior.html", null ],
    [ "MainMenuVersusElement", "class_main_menu_versus_element.html", null ],
    [ "Menu", "class_menu.html", null ],
    [ "MenuManager", "class_menu_manager.html", null ],
    [ "MouseInteractionComponent", "class_mouse_interaction_component.html", "class_mouse_interaction_component" ],
    [ "NotificationElement", "class_notification_element.html", null ],
    [ "NotificationManager", "class_notification_manager.html", "class_notification_manager" ],
    [ "Notifications", "class_notifications.html", null ],
    [ "OnGoingBattleLobbyListPageElement", "class_on_going_battle_lobby_list_page_element.html", null ],
    [ "OnOffButton", "class_on_off_button.html", null ],
    [ "OpenToInvite", "class_open_to_invite.html", null ],
    [ "OrientationManager", "class_orientation_manager.html", null ],
    [ "Overlays", "class_overlays.html", null ],
    [ "OverlaysManager", "class_overlays_manager.html", null ],
    [ "PlayerPrefsUtility", "class_player_prefs_utility.html", null ],
    [ "PlayerTournamentViewerElement", "class_player_tournament_viewer_element.html", null ],
    [ "Popup", "class_popup.html", null ],
    [ "PopupNotification", "class_popup_notification.html", null ],
    [ "ProfilePanel", "class_profile_panel.html", null ],
    [ "PWAPopup", "class_p_w_a_popup.html", null ],
    [ "QueryHelper", "class_query_helper.html", null ],
    [ "QuickFightComponent", "class_quick_fight_component.html", null ],
    [ "QuickFiightPanel", "class_quick_fiight_panel.html", null ],
    [ "ReactCommunicationComponent", "class_react_communication_component.html", null ],
    [ "ReceivedInvLobbyListPageElement", "class_received_inv_lobby_list_page_element.html", null ],
    [ "RulesPopup", "class_rules_popup.html", null ],
    [ "ScrollingText", "class_scrolling_text.html", null ],
    [ "SettingsPanel", "class_settings_panel.html", null ],
    [ "SlidingMenu", "class_sliding_menu.html", null ],
    [ "SNSUsernameTextComponent", "class_s_n_s_username_text_component.html", "class_s_n_s_username_text_component" ],
    [ "Sound", "class_sound.html", null ],
    [ "SoundCombatBlobArena", "class_sound_combat_blob_arena.html", null ],
    [ "SoundCombatCommon", "class_sound_combat_common.html", null ],
    [ "SoundCombatSpecial", "class_sound_combat_special.html", null ],
    [ "SoundEffect", "class_sound_effect.html", null ],
    [ "SoundVocals", "class_sound_vocals.html", null ],
    [ "SpeachBubble", "class_speach_bubble.html", "class_speach_bubble" ],
    [ "StandardButton", "class_standard_button.html", "class_standard_button" ],
    [ "StandardButtonType", "class_standard_button_type.html", "class_standard_button_type" ],
    [ "SwitchComponent", "class_switch_component.html", "class_switch_component" ],
    [ "TextColourChangeListener", "class_text_colour_change_listener.html", null ],
    [ "ThemeChangeAnimation", "class_theme_change_animation.html", null ],
    [ "ThemeColourListener", "class_theme_colour_listener.html", null ],
    [ "ThemeSelectorPageBehaviour", "class_theme_selector_page_behaviour.html", null ],
    [ "ToggleComponent", "class_toggle_component.html", "class_toggle_component" ],
    [ "TokenSelectionDropDownElement", "class_token_selection_drop_down_element.html", null ],
    [ "TournamentBannerComponent", "class_tournament_banner_component.html", null ],
    [ "TournamentDetailsPageBehaviour", "class_tournament_details_page_behaviour.html", null ],
    [ "TournamentFightElement", "class_tournament_fight_element.html", null ],
    [ "TournamentListElement", "class_tournament_list_element.html", "class_tournament_list_element" ],
    [ "TournamentListPageBehaviour", "class_tournament_list_page_behaviour.html", "class_tournament_list_page_behaviour" ],
    [ "TournamentLobbyPageBehaviour", "class_tournament_lobby_page_behaviour.html", null ],
    [ "TournamentMenuPageBehaviour", "class_tournament_menu_page_behaviour.html", null ],
    [ "TournamentSubMenu", "class_tournament_sub_menu.html", null ],
    [ "TournamentTypeSelector", "class_tournament_type_selector.html", null ],
    [ "Typewriter", "class_typewriter.html", "class_typewriter" ],
    [ "WagerConfirmationPopup", "class_wager_confirmation_popup.html", null ],
    [ "WagerPanel", "class_wager_panel.html", null ],
    [ "WalletSelector", "class_wallet_selector.html", null ],
    [ "WorldEntityTester", "class_world_entity_tester.html", null ],
    [ "XpBar", "class_xp_bar.html", "class_xp_bar" ],
    [ "YourFightListElement", "class_your_fight_list_element.html", null ],
    [ "YourFightsSubMenu", "class_your_fights_sub_menu.html", null ]
];